# Generated by Django 5.0 on 2023-12-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_alter_muallif_ism_alter_muallif_yosh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='sana',
            field=models.DateField(),
        ),
    ]
